### ISSUE TITLE
Mention other open source projects

### ISSUE THREAD

**Issue by pierreozoux** [mongrov/roverz#1]
As you are using wekan and RocketChat, I'd find it nice if you mention these projects on your website, especially on the open source page.
(maybe it is, but after 5min, didn't manage to find it)

**Comment by elarasu** [comment]
Thank you for the feedback. 

Our enterprise solution (mongrov.com) uses other open source packages as well (we will add all the packages that we use).  

We have opened up this first package on client that uses Rocket.Chat and if you see in this project, we have made it very clear that its tied to Rocket.Chat.

**Comment by pierreozoux** [comment]
Yes, true, it is part of the description :) Good luck for your business!
