### ISSUE TITLE
how to setup push-notifications?

### ISSUE THREAD

**Issue by zofe** [mongrov/roverz#3]
I've a custom rocket.chat instance, I'm trying to understand how to setup push-notifications on each side:  
- firebase cloud messaging (ex GCM)
- rocket.chat administration
- roverz configuration

help is appreciated

thanks

**Comment by elarasu** [comment]
Happy new year. Sorry didn't follow up earlier.

Setting up notifications is standard process as mentioned in https://github.com/zo0r/react-native-push-notification.   Please follow the instructions mentioned in this project and setup the appropriate configuration on server (pls make sure you restart it) and you are good to go.
